# **Agenda:**
## **Decision Tree Classifier**
<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Problem-Statement" data-toc-modified-id="Problem-Statement-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Problem Statement</a></span><ul class="toc-item"><li><span><a href="#What-is-a-Backorder?" data-toc-modified-id="What-is-a-Backorder?-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>What is a Backorder?</a></span></li><li><span><a href="#Data-description" data-toc-modified-id="Data-description-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Data description</a></span></li></ul></li><li><span><a href="#Loading-the-required-libraries" data-toc-modified-id="Loading-the-required-libraries-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Loading the required libraries</a></span></li><li><span><a href="#Identify-Right-Error-Metrics" data-toc-modified-id="Identify-Right-Error-Metrics-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Identify Right Error Metrics</a></span><ul class="toc-item"><li><span><a href="#Function-to-calculate-required-metrics" data-toc-modified-id="Function-to-calculate-required-metrics-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Function to calculate required metrics</a></span></li></ul></li><li><span><a href="#Loading-the-data" data-toc-modified-id="Loading-the-data-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Loading the data</a></span></li><li><span><a href="#Understand-the-Data-----Exploratory-Data-Analysis-(EDA)" data-toc-modified-id="Understand-the-Data-----Exploratory-Data-Analysis-(EDA)-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Understand the Data - - Exploratory Data Analysis (EDA)</a></span><ul class="toc-item"><li><span><a href="#Number-row-and-columns" data-toc-modified-id="Number-row-and-columns-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Number row and columns</a></span></li><li><span><a href="#First-and-last-5-records" data-toc-modified-id="First-and-last-5-records-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>First and last 5 records</a></span></li><li><span><a href="#Statistic-summary" data-toc-modified-id="Statistic-summary-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Statistic summary</a></span></li><li><span><a href="#Data-type" data-toc-modified-id="Data-type-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Data type</a></span></li></ul></li><li><span><a href="#Data-pre-processing" data-toc-modified-id="Data-pre-processing-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Data pre-processing</a></span><ul class="toc-item"><li><span><a href="#Convert-all-the-attributes-to-appropriate-type" data-toc-modified-id="Convert-all-the-attributes-to-appropriate-type-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Convert all the attributes to appropriate type</a></span><ul class="toc-item"><li><span><a href="#Re-display-data-type-of-each-variable" data-toc-modified-id="Re-display-data-type-of-each-variable-6.1.1"><span class="toc-item-num">6.1.1&nbsp;&nbsp;</span>Re-display data type of each variable</a></span></li><li><span><a href="#Statistic-summary" data-toc-modified-id="Statistic-summary-6.1.2"><span class="toc-item-num">6.1.2&nbsp;&nbsp;</span>Statistic summary</a></span></li></ul></li><li><span><a href="#Delete-sku-attribute" data-toc-modified-id="Delete-sku-attribute-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Delete sku attribute</a></span></li><li><span><a href="#Missing-Data" data-toc-modified-id="Missing-Data-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>Missing Data</a></span></li><li><span><a href="#Encoding-Categorical-to-Numeric" data-toc-modified-id="Encoding-Categorical-to-Numeric-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>Encoding Categorical to Numeric</a></span></li><li><span><a href="#Train-and-test-split" data-toc-modified-id="Train-and-test-split-6.5"><span class="toc-item-num">6.5&nbsp;&nbsp;</span>Train and test split</a></span><ul class="toc-item"><li><span><a href="#Target-attribute-distribution" data-toc-modified-id="Target-attribute-distribution-6.5.1"><span class="toc-item-num">6.5.1&nbsp;&nbsp;</span>Target attribute distribution</a></span></li><li><span><a href="#Split-the-data-into-train-and-test" data-toc-modified-id="Split-the-data-into-train-and-test-6.5.2"><span class="toc-item-num">6.5.2&nbsp;&nbsp;</span>Split the data into train and test</a></span></li><li><span><a href="#Target-attribute-distribution-after-the-split" data-toc-modified-id="Target-attribute-distribution-after-the-split-6.5.3"><span class="toc-item-num">6.5.3&nbsp;&nbsp;</span>Target attribute distribution after the split</a></span></li></ul></li></ul></li><li><span><a href="#Model-building" data-toc-modified-id="Model-building-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Model building</a></span><ul class="toc-item"><li><span><a href="#Decision-Tree-Model" data-toc-modified-id="Decision-Tree-Model-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Decision Tree Model</a></span><ul class="toc-item"><li><span><a href="#Instantiate-Model" data-toc-modified-id="Instantiate-Model-7.1.1"><span class="toc-item-num">7.1.1&nbsp;&nbsp;</span>Instantiate Model</a></span></li><li><span><a href="#Train-Model" data-toc-modified-id="Train-Model-7.1.2"><span class="toc-item-num">7.1.2&nbsp;&nbsp;</span>Train Model</a></span></li><li><span><a href="#List-important-features" data-toc-modified-id="List-important-features-7.1.3"><span class="toc-item-num">7.1.3&nbsp;&nbsp;</span>List important features</a></span></li><li><span><a href="#Display-Tree" data-toc-modified-id="Display-Tree-7.1.4"><span class="toc-item-num">7.1.4&nbsp;&nbsp;</span>Display Tree</a></span></li><li><span><a href="#Predict" data-toc-modified-id="Predict-7.1.5"><span class="toc-item-num">7.1.5&nbsp;&nbsp;</span>Predict</a></span></li><li><span><a href="#Evaluate" data-toc-modified-id="Evaluate-7.1.6"><span class="toc-item-num">7.1.6&nbsp;&nbsp;</span>Evaluate</a></span></li><li><span><a href="#Observation:" data-toc-modified-id="Observation:-7.1.7"><span class="toc-item-num">7.1.7&nbsp;&nbsp;</span>Observation:</a></span></li></ul></li><li><span><a href="#Up-sampling" data-toc-modified-id="Up-sampling-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Up-sampling</a></span><ul class="toc-item"><li><span><a href="#Instantiate-SMOTE" data-toc-modified-id="Instantiate-SMOTE-7.2.1"><span class="toc-item-num">7.2.1&nbsp;&nbsp;</span>Instantiate SMOTE</a></span></li><li><span><a href="#Fit-Sample" data-toc-modified-id="Fit-Sample-7.2.2"><span class="toc-item-num">7.2.2&nbsp;&nbsp;</span>Fit Sample</a></span></li></ul></li><li><span><a href="#Decision-Tree-with-up-sample-data" data-toc-modified-id="Decision-Tree-with-up-sample-data-7.3"><span class="toc-item-num">7.3&nbsp;&nbsp;</span>Decision Tree with up-sample data</a></span><ul class="toc-item"><li><span><a href="#Instantiate-Model" data-toc-modified-id="Instantiate-Model-7.3.1"><span class="toc-item-num">7.3.1&nbsp;&nbsp;</span>Instantiate Model</a></span></li><li><span><a href="#Train-the-model" data-toc-modified-id="Train-the-model-7.3.2"><span class="toc-item-num">7.3.2&nbsp;&nbsp;</span>Train the model</a></span></li><li><span><a href="#List-important-features" data-toc-modified-id="List-important-features-7.3.3"><span class="toc-item-num">7.3.3&nbsp;&nbsp;</span>List important features</a></span></li><li><span><a href="#Predict" data-toc-modified-id="Predict-7.3.4"><span class="toc-item-num">7.3.4&nbsp;&nbsp;</span>Predict</a></span></li><li><span><a href="#Evaluate" data-toc-modified-id="Evaluate-7.3.5"><span class="toc-item-num">7.3.5&nbsp;&nbsp;</span>Evaluate</a></span></li></ul></li><li><span><a href="#Hyper-parameter-tuning-using-Grid-Search-and-Cross-Validation" data-toc-modified-id="Hyper-parameter-tuning-using-Grid-Search-and-Cross-Validation-7.4"><span class="toc-item-num">7.4&nbsp;&nbsp;</span>Hyper-parameter tuning using Grid Search and Cross Validation</a></span><ul class="toc-item"><li><span><a href="#Cross-validation" data-toc-modified-id="Cross-validation-7.4.1"><span class="toc-item-num">7.4.1&nbsp;&nbsp;</span>Cross validation</a></span></li><li><span><a href="#Two-type-of-Machine-Learning-Model-Parameters" data-toc-modified-id="Two-type-of-Machine-Learning-Model-Parameters-7.4.2"><span class="toc-item-num">7.4.2&nbsp;&nbsp;</span>Two type of Machine Learning Model Parameters</a></span></li><li><span><a href="#Lets-list-the-hyper-parameters-for-Decision-Trees:" data-toc-modified-id="Lets-list-the-hyper-parameters-for-Decision-Trees:-7.4.3"><span class="toc-item-num">7.4.3&nbsp;&nbsp;</span>Lets list the hyper-parameters for Decision Trees:</a></span></li><li><span><a href="#Parameters-to-test" data-toc-modified-id="Parameters-to-test-7.4.4"><span class="toc-item-num">7.4.4&nbsp;&nbsp;</span>Parameters to test</a></span></li><li><span><a href="#Instantiate-Decision-Tree" data-toc-modified-id="Instantiate-Decision-Tree-7.4.5"><span class="toc-item-num">7.4.5&nbsp;&nbsp;</span>Instantiate Decision Tree</a></span></li><li><span><a href="#GridSearchCV" data-toc-modified-id="GridSearchCV-7.4.6"><span class="toc-item-num">7.4.6&nbsp;&nbsp;</span>GridSearchCV</a></span></li><li><span><a href="#Train" data-toc-modified-id="Train-7.4.7"><span class="toc-item-num">7.4.7&nbsp;&nbsp;</span>Train</a></span></li><li><span><a href="#Best-Params" data-toc-modified-id="Best-Params-7.4.8"><span class="toc-item-num">7.4.8&nbsp;&nbsp;</span>Best Params</a></span></li><li><span><a href="#Predict" data-toc-modified-id="Predict-7.4.9"><span class="toc-item-num">7.4.9&nbsp;&nbsp;</span>Predict</a></span></li><li><span><a href="#Evaluate" data-toc-modified-id="Evaluate-7.4.10"><span class="toc-item-num">7.4.10&nbsp;&nbsp;</span>Evaluate</a></span></li></ul></li><li><span><a href="#Building-Decision-Tree-Model-using-Variable-Importance" data-toc-modified-id="Building-Decision-Tree-Model-using-Variable-Importance-7.5"><span class="toc-item-num">7.5&nbsp;&nbsp;</span>Building Decision Tree Model using Variable Importance</a></span><ul class="toc-item"><li><span><a href="#Instantiate-Model" data-toc-modified-id="Instantiate-Model-7.5.1"><span class="toc-item-num">7.5.1&nbsp;&nbsp;</span>Instantiate Model</a></span></li><li><span><a href="#Train-the-model" data-toc-modified-id="Train-the-model-7.5.2"><span class="toc-item-num">7.5.2&nbsp;&nbsp;</span>Train the model</a></span></li><li><span><a href="#Predict" data-toc-modified-id="Predict-7.5.3"><span class="toc-item-num">7.5.3&nbsp;&nbsp;</span>Predict</a></span></li><li><span><a href="#Evaluate" data-toc-modified-id="Evaluate-7.5.4"><span class="toc-item-num">7.5.4&nbsp;&nbsp;</span>Evaluate</a></span></li></ul></li></ul></li></ul></div>

# Problem Statement

Is to identify products at risk of backorder before the event occurs so that business has time to react. 

## What is a Backorder?

* Backorders are products that are temporarily out of stock, but a customer is permitted to place an order against future inventory. 
* A backorder generally indicates that customer demand for a product or service exceeds a company’s capacity to supply it. 
* Back orders are both good and bad. Strong demand can drive back orders, but so can suboptimal planning. 

## Data description

Data file contains the historical data for the 8 weeks prior to the week we are trying to predict. The data was taken as weekly snapshots at the start of each week. Columns are defined as follows:

    sku - Random ID for the product

    national_inv - Current inventory level for the part

    lead_time - Transit time for product (if available)

    in_transit_qty - Amount of product in transit from source

    forecast_3_month - Forecast sales for the next 3 months

    forecast_6_month - Forecast sales for the next 6 months

    forecast_9_month - Forecast sales for the next 9 months

    sales_1_month - Sales quantity for the prior 1 month time period

    sales_3_month - Sales quantity for the prior 3 month time period

    sales_6_month - Sales quantity for the prior 6 month time period

    sales_9_month - Sales quantity for the prior 9 month time period

    min_bank - Minimum recommend amount to stock

    potential_issue - Source issue for part identified

    pieces_past_due - Parts overdue from source

    perf_6_month_avg - Source performance for prior 6 month period

    perf_12_month_avg - Source performance for prior 12 month period

    local_bo_qty - Amount of stock orders overdue

    deck_risk - Part risk flag

    oe_constraint - Part risk flag

    ppap_risk - Part risk flag

    stop_auto_buy - Part risk flag

    rev_stop - Part risk flag

    went_on_backorder - Product actually went on backorder. This is the target value.
    
         Yes or 1 : Product backordered

         No or 0  : Product not backordered

#### Broad Classification of attributes

SKU  : Unique material identifier;

INV  : Current inventory level of material;

TIM  : Registered transit time;

FOR  : Forecast sales for the next 3, 6, and 9 months;

SAL  : Sales quantity for the prior 1, 3, 5, and 9 months;

MIN  : Minimum recommended amount in stock (MIN);

OVRP : Parts overdue from source;

SUP  : Supplier performance in last 1 and 2 semesters;

OVRA : Amount of stock orders overdue (OVRA);

RSK  : General risk flags associated to the material;

BO   : Product went on backorder

# Installing Necessary Packages

In [2]:
!pip install graphviz
!pip install imblearn

In [3]:
import warnings
warnings.filterwarnings("ignore")

# Loading the required libraries

In [4]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score

from imblearn.over_sampling import SMOTE

import graphviz

## Function to calculate required metrics

In [5]:
def evaluate_model(act, pred):
    print("Confusion Matrix \n", confusion_matrix(act, pred))
    print("Accurcay : ", accuracy_score(act, pred))
    print("Recall   : ", recall_score(act, pred))
    print("Precision: ", precision_score(act, pred))    

# Loading the data

In [7]:
data = pd.read_excel("C:/Users/gsk44/OneDrive/Desktop/DecisionTree/Decision Tree Classification/BackOrders.xlsx", header=0)

# Understand the Data - - Exploratory Data Analysis (EDA)

## Number row and columns

In [8]:
data.shape

(61589, 23)

In [9]:
data.columns

Index(['sku', 'national_inv', 'lead_time', 'in_transit_qty',
       'forecast_3_month', 'forecast_6_month', 'forecast_9_month',
       'sales_1_month', 'sales_3_month', 'sales_6_month', 'sales_9_month',
       'min_bank', 'potential_issue', 'pieces_past_due', 'perf_6_month_avg',
       'perf_12_month_avg', 'local_bo_qty', 'deck_risk', 'oe_constraint',
       'ppap_risk', 'stop_auto_buy', 'rev_stop', 'went_on_backorder'],
      dtype='object')

## First and last 5 records

In [10]:
data.head()

sku  national_inv  lead_time  in_transit_qty  forecast_3_month  \
0  1888279           117        NaN               0                 0   
1  1870557             7        2.0               0                 0   
2  1475481           258       15.0              10                10   
3  1758220            46        2.0               0                 0   
4  1360312             2        2.0               0                 4   

   forecast_6_month  forecast_9_month  sales_1_month  sales_3_month  \
0                 0                 0              0              0   
1                 0                 0              0              0   
2                77               184             46            132   
3                 0                 0              1              2   
4                 6                10              2              2   

   sales_6_month  ...  pieces_past_due  perf_6_month_avg perf_12_month_avg  \
0             15  ...                0            -99.00            -99.00   
1              0  ...                0              0.50              0.28   
2            256  ...                0              0.54              0.70   
3              6  ...                0              0.75              0.90   
4              5  ...                0              0.97              0.92   

   local_bo_qty  deck_risk  oe_constraint  ppap_risk stop_auto_buy rev_stop  \
0             0         No             No        Yes           Yes       No   
1             0        Yes             No         No           Yes       No   
2             0         No             No         No           Yes       No   
3             0        Yes             No         No           Yes       No   
4             0         No             No         No           Yes       No   

  went_on_backorder  
0                No  
1                No  
2                No  
3                No  
4                No  

[5 rows x 23 columns]

In [11]:
data.tail()

sku  national_inv  lead_time  in_transit_qty  forecast_3_month  \
61584  1397275             6        8.0               0                24   
61585  3072139           130        2.0               0                40   
61586  1909363           135        9.0               0                 0   
61587  1845783            63        NaN               0                 0   
61588  1200539             0        2.0               0                 8   

       forecast_6_month  forecast_9_month  sales_1_month  sales_3_month  \
61584                24                24              0              7   
61585                80               140             18            108   
61586                 0                 0             10             40   
61587                 0                 0            452           1715   
61588                 8                 8              0              1   

       sales_6_month  ...  pieces_past_due  perf_6_month_avg  \
61584              9  ...                0              0.98   
61585            230  ...                0              0.51   
61586             65  ...                0              1.00   
61587           3425  ...                0            -99.00   
61588              1  ...                0              0.79   

      perf_12_month_avg  local_bo_qty  deck_risk  oe_constraint  ppap_risk  \
61584              0.98             0         No             No         No   
61585              0.28             0         No             No         No   
61586              0.99             0         No             No        Yes   
61587            -99.00             1         No             No         No   
61588              0.78             0        Yes             No         No   

      stop_auto_buy rev_stop went_on_backorder  
61584           Yes       No                No  
61585           Yes       No                No  
61586           Yes       No                No  
61587            No       No               Yes  
61588           Yes       No               Yes  

[5 rows x 23 columns]

## Statistic summary 


In [12]:
data.describe(include='all')

sku   national_inv     lead_time  in_transit_qty  \
count   6.158900e+04   61589.000000  58186.000000    61589.000000   
unique           NaN            NaN           NaN             NaN   
top              NaN            NaN           NaN             NaN   
freq             NaN            NaN           NaN             NaN   
mean    2.037188e+06     287.721882      7.559619       30.192843   
std     6.564178e+05    4233.906931      6.498952      792.869253   
min     1.068628e+06   -2999.000000      0.000000        0.000000   
25%     1.498574e+06       3.000000      4.000000        0.000000   
50%     1.898033e+06      10.000000      8.000000        0.000000   
75%     2.314826e+06      57.000000      8.000000        0.000000   
max     3.284895e+06  673445.000000     52.000000   170976.000000   

        forecast_3_month  forecast_6_month  forecast_9_month  sales_1_month  \
count       6.158900e+04      6.158900e+04      6.158900e+04   61589.000000   
unique               NaN               NaN               NaN            NaN   
top                  NaN               NaN               NaN            NaN   
freq                 NaN               NaN               NaN            NaN   
mean        1.692728e+02      3.150413e+02      4.535760e+02      44.742957   
std         5.286742e+03      9.774362e+03      1.420201e+04    1373.805831   
min         0.000000e+00      0.000000e+00      0.000000e+00       0.000000   
25%         0.000000e+00      0.000000e+00      0.000000e+00       0.000000   
50%         0.000000e+00      0.000000e+00      0.000000e+00       0.000000   
75%         1.200000e+01      2.500000e+01      3.600000e+01       6.000000   
max         1.126656e+06      2.094336e+06      3.062016e+06  295197.000000   

        sales_3_month  sales_6_month  ...  pieces_past_due  perf_6_month_avg  \
count    61589.000000   6.158900e+04  ...     61589.000000      61589.000000   
unique            NaN            NaN  ...              NaN               NaN   
top               NaN            NaN  ...              NaN               NaN   
freq              NaN            NaN  ...              NaN               NaN   
mean       150.732631   2.835465e+02  ...         1.605400         -6.264182   
std       5224.959649   8.872270e+03  ...        42.309229         25.537906   
min          0.000000   0.000000e+00  ...         0.000000        -99.000000   
25%          0.000000   0.000000e+00  ...         0.000000          0.620000   
50%          2.000000   4.000000e+00  ...         0.000000          0.820000   
75%         17.000000   3.400000e+01  ...         0.000000          0.960000   
max     934593.000000   1.799099e+06  ...      7392.000000          1.000000   

       perf_12_month_avg  local_bo_qty  deck_risk  oe_constraint  ppap_risk  \
count       61589.000000  61589.000000      61589          61589      61589   
unique               NaN           NaN          2              2          2   
top                  NaN           NaN         No             No         No   
freq                 NaN           NaN      48145          61577      53792   
mean           -5.863664      1.205361        NaN            NaN        NaN   
std            24.844514     29.981155        NaN            NaN        NaN   
min           -99.000000      0.000000        NaN            NaN        NaN   
25%             0.640000      0.000000        NaN            NaN        NaN   
50%             0.800000      0.000000        NaN            NaN        NaN   
75%             0.950000      0.000000        NaN            NaN        NaN   
max             1.000000   2999.000000        NaN            NaN        NaN   

       stop_auto_buy rev_stop went_on_backorder  
count          61589    61589             61589  
unique             2        2                 2  
top              Yes       No                No  
freq           59303    61569             50296  
mean             NaN      NaN               NaN  
std              NaN      NaN

## Data type

In [13]:
data.dtypes

sku                    int64
national_inv           int64
lead_time            float64
in_transit_qty         int64
forecast_3_month       int64
forecast_6_month       int64
forecast_9_month       int64
sales_1_month          int64
sales_3_month          int64
sales_6_month          int64
sales_9_month          int64
min_bank               int64
potential_issue       object
pieces_past_due        int64
perf_6_month_avg     float64
perf_12_month_avg    float64
local_bo_qty           int64
deck_risk             object
oe_constraint         object
ppap_risk             object
stop_auto_buy         object
rev_stop              object
went_on_backorder     object
dtype: object

# Data pre-processing

## Convert all the attributes to appropriate type

In [14]:
for col in ['sku', 'potential_issue', 'deck_risk', 'oe_constraint', 'ppap_risk', 
            'stop_auto_buy', 'rev_stop', 'went_on_backorder']:
    data[col] = data[col].astype('category')

### Re-display data type of each variable

In [15]:
data.dtypes

sku                  category
national_inv            int64
lead_time             float64
in_transit_qty          int64
forecast_3_month        int64
forecast_6_month        int64
forecast_9_month        int64
sales_1_month           int64
sales_3_month           int64
sales_6_month           int64
sales_9_month           int64
min_bank                int64
potential_issue      category
pieces_past_due         int64
perf_6_month_avg      float64
perf_12_month_avg     float64
local_bo_qty            int64
deck_risk            category
oe_constraint        category
ppap_risk            category
stop_auto_buy        category
rev_stop             category
went_on_backorder    category
dtype: object

### Statistic summary 


In [16]:
data.describe(include='all')

sku   national_inv     lead_time  in_transit_qty  \
count     61589.0   61589.000000  58186.000000    61589.000000   
unique    61589.0            NaN           NaN             NaN   
top     1068628.0            NaN           NaN             NaN   
freq          1.0            NaN           NaN             NaN   
mean          NaN     287.721882      7.559619       30.192843   
std           NaN    4233.906931      6.498952      792.869253   
min           NaN   -2999.000000      0.000000        0.000000   
25%           NaN       3.000000      4.000000        0.000000   
50%           NaN      10.000000      8.000000        0.000000   
75%           NaN      57.000000      8.000000        0.000000   
max           NaN  673445.000000     52.000000   170976.000000   

        forecast_3_month  forecast_6_month  forecast_9_month  sales_1_month  \
count       6.158900e+04      6.158900e+04      6.158900e+04   61589.000000   
unique               NaN               NaN               NaN            NaN   
top                  NaN               NaN               NaN            NaN   
freq                 NaN               NaN               NaN            NaN   
mean        1.692728e+02      3.150413e+02      4.535760e+02      44.742957   
std         5.286742e+03      9.774362e+03      1.420201e+04    1373.805831   
min         0.000000e+00      0.000000e+00      0.000000e+00       0.000000   
25%         0.000000e+00      0.000000e+00      0.000000e+00       0.000000   
50%         0.000000e+00      0.000000e+00      0.000000e+00       0.000000   
75%         1.200000e+01      2.500000e+01      3.600000e+01       6.000000   
max         1.126656e+06      2.094336e+06      3.062016e+06  295197.000000   

        sales_3_month  sales_6_month  ...  pieces_past_due  perf_6_month_avg  \
count    61589.000000   6.158900e+04  ...     61589.000000      61589.000000   
unique            NaN            NaN  ...              NaN               NaN   
top               NaN            NaN  ...              NaN               NaN   
freq              NaN            NaN  ...              NaN               NaN   
mean       150.732631   2.835465e+02  ...         1.605400         -6.264182   
std       5224.959649   8.872270e+03  ...        42.309229         25.537906   
min          0.000000   0.000000e+00  ...         0.000000        -99.000000   
25%          0.000000   0.000000e+00  ...         0.000000          0.620000   
50%          2.000000   4.000000e+00  ...         0.000000          0.820000   
75%         17.000000   3.400000e+01  ...         0.000000          0.960000   
max     934593.000000   1.799099e+06  ...      7392.000000          1.000000   

       perf_12_month_avg  local_bo_qty  deck_risk  oe_constraint  ppap_risk  \
count       61589.000000  61589.000000      61589          61589      61589   
unique               NaN           NaN          2              2          2   
top                  NaN           NaN         No             No         No   
freq                 NaN           NaN      48145          61577      53792   
mean           -5.863664      1.205361        NaN            NaN        NaN   
std            24.844514     29.981155        NaN            NaN        NaN   
min           -99.000000      0.000000        NaN            NaN        NaN   
25%             0.640000      0.000000        NaN            NaN        NaN   
50%             0.800000      0.000000        NaN            NaN        NaN   
75%             0.950000      0.000000        NaN            NaN        NaN   
max             1.000000   2999.000000        NaN            NaN        NaN   

       stop_auto_buy rev_stop went_on_backorder  
count          61589    61589             61589  
unique             2        2                 2  
top              Yes       No                No  
freq           59303    61569             50296  
mean             NaN      NaN               NaN  
std              NaN      NaN               NaN  
min         

## Delete sku attribute

In [17]:
np.size(np.unique(data.sku, return_counts=True)[0])

61589

In [18]:
data.drop('sku', axis=1, inplace=True)

## Missing Data

In [19]:
data.isnull().sum()

national_inv            0
lead_time            3403
in_transit_qty          0
forecast_3_month        0
forecast_6_month        0
forecast_9_month        0
sales_1_month           0
sales_3_month           0
sales_6_month           0
sales_9_month           0
min_bank                0
potential_issue         0
pieces_past_due         0
perf_6_month_avg        0
perf_12_month_avg       0
local_bo_qty            0
deck_risk               0
oe_constraint           0
ppap_risk               0
stop_auto_buy           0
rev_stop                0
went_on_backorder       0
dtype: int64

In [20]:
print (data.shape)

(61589, 22)


In [21]:
data = data.dropna(axis=0)

In [22]:
print(data.isnull().sum())
print(data.shape)

national_inv         0
lead_time            0
in_transit_qty       0
forecast_3_month     0
forecast_6_month     0
forecast_9_month     0
sales_1_month        0
sales_3_month        0
sales_6_month        0
sales_9_month        0
min_bank             0
potential_issue      0
pieces_past_due      0
perf_6_month_avg     0
perf_12_month_avg    0
local_bo_qty         0
deck_risk            0
oe_constraint        0
ppap_risk            0
stop_auto_buy        0
rev_stop             0
went_on_backorder    0
dtype: int64
(58186, 22)


## Encoding Categorical to Numeric

In [23]:
cat_attr_names = data.select_dtypes(include=['category']).columns

In [24]:
data = pd.get_dummies(columns=cat_attr_names, data=data, 
                      prefix=cat_attr_names, prefix_sep="_", drop_first=True)

In [25]:
print (data.columns, data.shape)

Index(['national_inv', 'lead_time', 'in_transit_qty', 'forecast_3_month',
       'forecast_6_month', 'forecast_9_month', 'sales_1_month',
       'sales_3_month', 'sales_6_month', 'sales_9_month', 'min_bank',
       'pieces_past_due', 'perf_6_month_avg', 'perf_12_month_avg',
       'local_bo_qty', 'potential_issue_Yes', 'deck_risk_Yes',
       'oe_constraint_Yes', 'ppap_risk_Yes', 'stop_auto_buy_Yes',
       'rev_stop_Yes', 'went_on_backorder_Yes'],
      dtype='object') (58186, 22)


## Train and test split

### Target attribute distribution 

In [26]:
data['went_on_backorder_Yes'].value_counts()

0    47217
1    10969
Name: went_on_backorder_Yes, dtype: int64

In [27]:
data['went_on_backorder_Yes'].value_counts(normalize=True)*100

0    81.148386
1    18.851614
Name: went_on_backorder_Yes, dtype: float64

### Split the data into train and test


In [28]:
X = data.drop('went_on_backorder_Yes', axis=1)
y = data['went_on_backorder_Yes']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=123) 

### Target attribute distribution after the split

In [29]:
print(pd.value_counts(y_train, normalize=True) * 100)

print(pd.value_counts(y_test, normalize=True) * 100)

0    81.185858
1    18.814142
Name: went_on_backorder_Yes, dtype: float64
0    81.060953
1    18.939047
Name: went_on_backorder_Yes, dtype: float64


# Model building

## Decision Tree Model

### Instantiate Model

In [30]:
dtclf = DecisionTreeClassifier()

### Train Model

In [31]:
dtclf.fit(X_train, y_train)

DecisionTreeClassifier()

### List important features

In [32]:
importances = dtclf.feature_importances_
importances

array([3.11309835e-01, 3.22438577e-02, 3.23331232e-02, 9.12421124e-02,
       2.77985279e-02, 1.11165583e-01, 7.01090178e-02, 3.59954277e-02,
       4.89508461e-02, 4.85661051e-02, 3.00008552e-02, 7.02262131e-03,
       5.69806229e-02, 6.33073065e-02, 9.98455135e-03, 1.82819429e-04,
       1.08879827e-02, 0.00000000e+00, 1.03404621e-02, 1.57834213e-03,
       0.00000000e+00])

In [33]:
indices = np.argsort(importances)[::-1]
ind_attr_names = X_train.columns
pd.DataFrame([ind_attr_names[indices], np.sort(importances)[::-1]])

0                 1                 2              3   \
0  national_inv  forecast_9_month  forecast_3_month  sales_1_month   
1       0.31131          0.111166          0.091242       0.070109   

                  4                 5              6              7   \
0  perf_12_month_avg  perf_6_month_avg  sales_6_month  sales_9_month   
1           0.063307          0.056981       0.048951       0.048566   

              8               9   ...        11                12  \
0  sales_3_month  in_transit_qty  ...  min_bank  forecast_6_month   
1       0.035995        0.032333  ...  0.030001          0.027799   

              13             14            15               16  \
0  deck_risk_Yes  ppap_risk_Yes  local_bo_qty  pieces_past_due   
1       0.010888        0.01034      0.009985         0.007023   

                  17                   18                 19            20  
0  stop_auto_buy_Yes  potential_issue_Yes  oe_constraint_Yes  rev_stop_Yes  
1           0.001578             0.000183                0.0           0.0  

[2 rows x 21 columns]

### Visualizing Decision Trees

In [34]:
dtclf.classes_

array([0, 1], dtype=uint8)

In [35]:
dot_data = export_graphviz(dtclf, 
                           feature_names=ind_attr_names,
                           class_names=['No', 'Yes'], 
                           filled=True) 

graph = graphviz.Source(dot_data) 

graph.render("/content/drive/My Drive/ML_LAB/DecisionTreeLab/Batch124/DTClassifier/ClassificationTree", view=True) 

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH

In [ ]:
# Decision Tree Graph explanation
dtclf2 = DecisionTreeClassifier(max_depth=2) # Change 1, 2, 3
dtclf2.fit(X_train, y_train)
dot_data2 = export_graphviz(dtclf2, 
                           feature_names=ind_attr_names,
                           class_names=['No', 'Yes'], 
                           filled=True) 

graph2 = graphviz.Source(dot_data2) 
graph2

### Predict

In [ ]:
train_pred = dtclf.predict(X_train)
test_pred = dtclf.predict(X_test)

### Evaluate

In [36]:
print("--Train--")
evaluate_model(y_train, train_pred)
print("--Test--")
evaluate_model(y_test, test_pred)

--Train--


NameError: name 'train_pred' is not defined

## SMOTE 

### Instantiate SMOTE

In [37]:
smote = SMOTE(random_state=123)

### Fit Sample

In [38]:
X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)

In [39]:
X_train_sm.shape

(66134, 21)

In [40]:
y_train_sm.shape

(66134,)

In [41]:
print(pd.value_counts(y_train_sm, normalize=True) * 100)

0    50.0
1    50.0
Name: went_on_backorder_Yes, dtype: float64


## Decision Tree with up-sample data

### Instantiate Model

In [42]:
dtclf2 = DecisionTreeClassifier()

### Train the model

In [43]:
dtclf2 = dtclf2.fit(X_train_sm, y_train_sm)

### List important features

In [44]:
importances = dtclf2.feature_importances_
importances

array([2.08139711e-01, 4.99421373e-02, 2.03621308e-02, 3.50805986e-01,
       2.44642649e-02, 2.81403802e-02, 3.88661951e-02, 4.49035733e-02,
       3.24726588e-02, 3.42617194e-02, 1.57640432e-02, 2.03264844e-02,
       5.21647065e-02, 5.38311787e-02, 9.25423583e-03, 2.35099574e-04,
       6.72635967e-03, 5.24503761e-05, 6.32776430e-03, 2.95892081e-03,
       0.00000000e+00])

In [45]:
indices = np.argsort(importances)[::-1]
pd.DataFrame([ind_attr_names[indices], np.sort(importances)[::-1]])

0             1                  2                 3   \
0  forecast_3_month  national_inv  perf_12_month_avg  perf_6_month_avg   
1          0.350806       0.20814           0.053831          0.052165   

          4              5              6              7              8   \
0  lead_time  sales_3_month  sales_1_month  sales_9_month  sales_6_month   
1   0.049942       0.044904       0.038866       0.034262       0.032473   

                 9   ...              11               12        13  \
0  forecast_9_month  ...  in_transit_qty  pieces_past_due  min_bank   
1           0.02814  ...        0.020362         0.020326  0.015764   

             14             15             16                 17  \
0  local_bo_qty  deck_risk_Yes  ppap_risk_Yes  stop_auto_buy_Yes   
1      0.009254       0.006726       0.006328           0.002959   

                    18                 19            20  
0  potential_issue_Yes  oe_constraint_Yes  rev_stop_Yes  
1             0.000235           0.000052           0.0  

[2 rows x 21 columns]

### Predict

In [46]:
train_pred=dtclf2.predict(X_train_sm)
test_pred=dtclf2.predict(X_test)

### Evaluate

In [47]:
print("--Train--")
evaluate_model(y_train_sm, train_pred)
print("--Test--")
evaluate_model(y_test, test_pred)

--Train--
Confusion Matrix 
 [[33020    47]
 [   64 33003]]
Accurcay :  0.9983215895001059
Recall   :  0.9980645356397617
Precision:  0.9985779122541604
--Test--
Confusion Matrix 
 [[12888  1262]
 [  591  2715]]
Accurcay :  0.8938473877176902
Recall   :  0.8212341197822142
Precision:  0.6826753834548654


## Hyper-parameter tuning using Grid Search and Cross Validation

### Parameters to test

In [48]:
param_grid = {"criterion": ["gini", "entropy"],
              "min_samples_split": [2, 5],
              "max_depth": [None, 2],
              "min_samples_leaf": [1, 5]
             }

### Instantiate Decision Tree

In [49]:
dtclf3 = DecisionTreeClassifier()

### GridSearchCV 

In [50]:
dtclf_grid = GridSearchCV(dtclf3, param_grid, cv=3)

### Train

In [51]:
dtclf_grid.fit(X_train_sm, y_train_sm)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 2], 'min_samples_leaf': [1, 5],
                         'min_samples_split': [2, 5]})

### Best Params

In [52]:
dtclf_grid.best_params_

{'criterion': 'entropy',
 'max_depth': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2}

### Predict 

In [53]:
train_pred = dtclf_grid.predict(X_train_sm)
test_pred = dtclf_grid.predict(X_test)

### Evaluate

In [54]:
print("--Train--")
evaluate_model(y_train_sm, train_pred)
print("--Test--")
evaluate_model(y_test, test_pred)

--Train--
Confusion Matrix 
 [[33020    47]
 [   64 33003]]
Accurcay :  0.9983215895001059
Recall   :  0.9980645356397617
Precision:  0.9985779122541604
--Test--
Confusion Matrix 
 [[12884  1266]
 [  601  2705]]
Accurcay :  0.8930453712190651
Recall   :  0.8182093163944344
Precision:  0.6811886174767061


## Building Decision Tree Model using Variable Importance

In [55]:
importances = dtclf_grid.best_estimator_.feature_importances_
importances

array([2.05540049e-01, 5.35174729e-02, 2.43744605e-02, 2.73675917e-01,
       3.28569410e-02, 3.74006031e-02, 3.83133231e-02, 3.35962960e-02,
       5.15037929e-02, 5.58379193e-02, 2.60928064e-02, 1.82110080e-02,
       6.01817771e-02, 6.26632223e-02, 7.75435074e-03, 7.34873141e-05,
       8.52933796e-03, 0.00000000e+00, 6.63945897e-03, 3.23777633e-03,
       0.00000000e+00])

In [56]:
indices = np.argsort(importances)[::-1]
print(indices)

[ 3  0 13 12  9  1  8  6  5  7  4 10  2 11 16 14 18 19 15 17 20]


In [57]:
select = indices[0:5]
print(select)

[ 3  0 13 12  9]


### Instantiate Model

In [58]:
dtclf3 = DecisionTreeClassifier(criterion= 'entropy', 
                                max_depth= None, 
                                min_samples_leaf= 1,
                                min_samples_split= 2)

### Train the model

In [59]:
dtclf3 = dtclf3.fit(X_train_sm.values[:,select], y_train_sm)

### Predict

In [60]:
train_pred = dtclf3.predict(X_train_sm.values[:,select])
test_pred = dtclf3.predict(X_test.values[:,select])

### Evaluate

In [61]:
print("--Train--")
evaluate_model(y_train_sm, train_pred)
print("--Test--")
evaluate_model(y_test, test_pred)

--Train--
Confusion Matrix 
 [[32856   211]
 [  237 32830]]
Accurcay :  0.9932258747391659
Recall   :  0.9928327335409926
Precision:  0.9936139947338155
--Test--
Confusion Matrix 
 [[12602  1548]
 [  651  2655]]
Accurcay :  0.8740261228230981
Recall   :  0.8030852994555354
Precision:  0.6316916488222698
